DROP TABLE IF EXISTS user;

CREATE TABLE users (
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);